version: '3'
services:
   db:
      image: mcr.microsoft.com/mssql/server:${MSSQL_VERSION}
      restart: unless-stopped
      ports:
       - "1433:1433"
      command: bash -c "chmod -R 777 /usr/src/sql/ & /usr/src/sql/entrypoint.sh & /opt/mssql/bin/sqlservr"
      volumes:
      - C:\linux\init_db:/usr/src/sql/
      - c:\Mssql\data:/var/opt/mssql/data
      - c:\Mssql\log:/var/opt/mssql/log
      - c:\Mssql\secrets:/var/opt/mssql/secrets
      environment:
         TZ: 'Asia/Ho_Chi_Minh'
         ACCEPT_EULA: 'Y'
         MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
         MSSQL_PID: 'Express'