version: '3'
services:
   db:
      image: mcr.microsoft.com/mssql/server:${MSSQL_VERSION}
      restart: unless-stopped
      ports:
       - "1433:1433"
      command: bash -c "chmod -R 777 /usr/src/sql/ & /usr/src/sql/entrypoint.sh & /opt/mssql/bin/sqlservr"
      volumes:
      - C:\linux\init_db:/usr/src/sql/
      - c:\Mssql\data:/var/opt/mssql/data
      - c:\Mssql\log:/var/opt/mssql/log
      - c:\Mssql\secrets:/var/opt/mssql/secrets
      environment:
         TZ: 'Asia/Ho_Chi_Minh'
         ACCEPT_EULA: 'Y'
         MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
         MSSQL_PID: 'Express'

   sonar:
      image: sonarqube:${SONAR_VERSION}
      privileged: true
      depends_on:
      - db
      restart: unless-stopped
      ports:
      - "9000:9000"
      volumes:
      - c:\Sonarqube\data:/opt/sonarqube/data
      - c:\Sonarqube\extensions:/opt/sonarqube/extensions
      - c:\Sonarqube\logs:/opt/sonarqube/logs
      environment:
         TZ: 'Asia/Ho_Chi_Minh'
         SONAR_JDBC_URL: jdbc:sqlserver://db;databaseName=sonar
         SONAR_JDBC_USERNAME: sa
         SONAR_JDBC_PASSWORD: ${MSSQL_SA_PASSWORD}

   teamcity:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - "8112:8111"
    volumes:
      - c:\linux\data_dir:/data/teamcity_server/datadir
      - c:\linux\teamcity-server-logs:/opt/teamcity/logs
    depends_on:
      - db

   teamcity-agent-1:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    privileged: true
    depends_on:
      - teamcity
      - db
    volumes:
      - c:\linux\agents\agent-1\conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start

   teamcity-agent-2:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    privileged: true
    depends_on:
      - teamcity
      - db
    volumes:
      - c:\linux\agents\agent-2\conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start

   octopus-server:
    image: octopusdeploy/octopusdeploy:${OCTOPUS_SERVER_TAG}
    privileged: ${PRIVILEGED}
    user: ${USER}
    environment:
      ACCEPT_EULA: ${ACCEPT_OCTOPUS_EULA}
      OCTOPUS_SERVER_NODE_NAME: ${OCTOPUS_SERVER_NODE_NAME}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      OCTOPUS_SERVER_BASE64_LICENSE: ${OCTOPUS_SERVER_BASE64_LICENSE}
      MASTER_KEY: ${MASTER_KEY}
      ADMIN_API_KEY: ${ADMIN_API_KEY}
      DISABLE_DIND: ${DISABLE_DIND}
    ports:
      - 8080:8080
      - 11111:10943
    depends_on:
      - db
    volumes:
      - c:\Octopus\repository:/repository
      - c:\Octopus\artifacts:/artifacts
      - c:\Octopus\taskLogs:/taskLogs
      - c:\Octopus\cache:/cache
      - c:\Octopus\import:/import